"""empty message

Revision ID: 1dedd3a0caf9
Revises: 
Create Date: 2020-04-16 06:39:22.476308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dedd3a0caf9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('image_file', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=77), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_confirmed', sa.DateTime(), nullable=True),
    sa.Column('is_over_18', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_email_public', sa.Boolean(), nullable=False),
    sa.Column('has_seen_tutorial', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('gamemaster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('descrip', sa.String(length=250), nullable=False),
    sa.Column('intro_text', sa.String(length=2800), nullable=True),
    sa.Column('gamemaster_id', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('date_published', sa.DateTime(), nullable=True),
    sa.Column('has_adult_content', sa.Boolean(), nullable=True),
    sa.Column('attr_a_name', sa.String(length=25), nullable=True),
    sa.Column('attr_b_name', sa.String(length=25), nullable=True),
    sa.Column('attr_c_name', sa.String(length=25), nullable=True),
    sa.Column('attr_a_descrip', sa.String(length=250), nullable=True),
    sa.Column('attr_b_descrip', sa.String(length=250), nullable=True),
    sa.Column('attr_c_descrip', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['gamemaster_id'], ['gamemaster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_sheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('attr_a', sa.Integer(), nullable=True),
    sa.Column('attr_b', sa.Integer(), nullable=True),
    sa.Column('attr_c', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_sheet')
    op.drop_table('campaign')
    op.drop_table('player')
    op.drop_table('gamemaster')
    op.drop_table('user')
    # ### end Alembic commands ###
