"""empty message

Revision ID: 2c55de91df73
Revises: 66ce16b10772
Create Date: 2020-04-15 15:58:56.243609

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2c55de91df73'
down_revision = '66ce16b10772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('attr_a_descrip', sa.String(length=250), nullable=True))
    op.add_column('campaign', sa.Column('attr_a_name', sa.String(length=60), nullable=True))
    op.add_column('campaign', sa.Column('attr_b_descrip', sa.String(length=250), nullable=True))
    op.add_column('campaign', sa.Column('attr_b_name', sa.String(length=60), nullable=True))
    op.add_column('campaign', sa.Column('attr_c_descrip', sa.String(length=250), nullable=True))
    op.add_column('campaign', sa.Column('attr_c_name', sa.String(length=60), nullable=True))
    op.add_column('campaign', sa.Column('is_published', sa.Boolean(), nullable=True))
    op.drop_column('campaign', 'mechanics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('mechanics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('campaign', 'is_published')
    op.drop_column('campaign', 'attr_c_name')
    op.drop_column('campaign', 'attr_c_descrip')
    op.drop_column('campaign', 'attr_b_name')
    op.drop_column('campaign', 'attr_b_descrip')
    op.drop_column('campaign', 'attr_a_name')
    op.drop_column('campaign', 'attr_a_descrip')
    # ### end Alembic commands ###
