"""empty message

Revision ID: 2c67cf5ee9e4
Revises: 
Create Date: 2020-04-14 03:11:25.642331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c67cf5ee9e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('image_file', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=77), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_confirmed', sa.DateTime(), nullable=True),
    sa.Column('is_over_18', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('gamemaster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_sheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('descrip', sa.String(length=250), nullable=False),
    sa.Column('gamemaster_id', sa.Integer(), nullable=False),
    sa.Column('character_sheet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_sheet_id'], ['character_sheet.id'], ),
    sa.ForeignKeyConstraint(['gamemaster_id'], ['gamemaster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaign')
    op.drop_table('character_sheet')
    op.drop_table('player')
    op.drop_table('gamemaster')
    op.drop_table('user')
    # ### end Alembic commands ###
