"""empty message

Revision ID: 38c609b0b28d
Revises: 325cdb836261
Create Date: 2020-04-15 00:38:44.611762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38c609b0b28d'
down_revision = '325cdb836261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('character_sheet', 'campaign_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('character_sheet', 'campaign_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
