"""empty message

Revision ID: 46be5c1af2cf
Revises: f37e7b499361
Create Date: 2020-04-15 16:34:46.998031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46be5c1af2cf'
down_revision = 'f37e7b499361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('date_published', sa.DateTime(), nullable=True))
    op.add_column('campaign', sa.Column('has_adult_content', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('has_seen_tutorial', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'has_seen_tutorial')
    op.drop_column('campaign', 'has_adult_content')
    op.drop_column('campaign', 'date_published')
    # ### end Alembic commands ###
