"""empty message

Revision ID: 656caaacf39c
Revises: 
Create Date: 2020-04-12 23:42:30.018535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656caaacf39c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_sheet',
    sa.Column('character_sheet_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('character_sheet_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('image_file', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_confirmed', sa.DateTime(), nullable=True),
    sa.Column('is_over_18', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('gamemaster',
    sa.Column('gamemaster_id', sa.Integer(), nullable=False),
    sa.Column('gamemaster_access', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gamemaster_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('gamemaster_id')
    )
    op.create_table('player',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('player_access', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('campaign',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('campaign_name', sa.String(length=120), nullable=False),
    sa.Column('campaign_descrip', sa.String(length=250), nullable=False),
    sa.Column('gamemaster_id', sa.Integer(), nullable=False),
    sa.Column('character_sheet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_sheet_id'], ['character_sheet.character_sheet_id'], ),
    sa.ForeignKeyConstraint(['gamemaster_id'], ['gamemaster.gamemaster_id'], ),
    sa.PrimaryKeyConstraint('campaign_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaign')
    op.drop_table('player')
    op.drop_table('gamemaster')
    op.drop_table('user')
    op.drop_table('character_sheet')
    # ### end Alembic commands ###
