"""empty message

Revision ID: 66ce16b10772
Revises: 38c609b0b28d
Create Date: 2020-04-15 15:19:00.852992

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '66ce16b10772'
down_revision = '38c609b0b28d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('mechanics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign', 'mechanics')
    # ### end Alembic commands ###
