"""empty message

Revision ID: a3c95534aeba
Revises: 2c55de91df73
Create Date: 2020-04-15 16:05:19.145768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3c95534aeba'
down_revision = '2c55de91df73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('intro_text', sa.String(length=2800), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign', 'intro_text')
    # ### end Alembic commands ###
