"""empty message

Revision ID: f37e7b499361
Revises: a3c95534aeba
Create Date: 2020-04-15 16:06:56.773474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f37e7b499361'
down_revision = 'a3c95534aeba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character_sheet', sa.Column('attr_a', sa.Integer(), nullable=True))
    op.add_column('character_sheet', sa.Column('attr_b', sa.Integer(), nullable=True))
    op.add_column('character_sheet', sa.Column('attr_c', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character_sheet', 'attr_c')
    op.drop_column('character_sheet', 'attr_b')
    op.drop_column('character_sheet', 'attr_a')
    # ### end Alembic commands ###
